server:
  port: 8080
spring:
  application:
    name: zuul

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      url: http://localhost:8081/auth-service/
    admin-service:
      path: /admin-service/**
      url: http://localhost:8082/admin-service/
    search-service:
      path: /search-service/**
      url: http://localhost:8088/search-service/
    posting-service:
      path: /posting-service/**
      url: http://localhost:8085/posting-service/
    review-service:
      path: /review-service/**
      url: http://localhost:8087/review-service/
