server:
  port: 8080
spring:
  application:
    name: zuul

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 10000

zuul:
  routes:
    auth-service:
      path: /auth-service/**
      url: http://localhost:8081/auth-service/
    admin-service:
      path: /admin-service/**
      url: http://localhost:8082/admin-service/
    search-service:
      path: /search-service/**
      url: http://localhost:8088/search-service/
    posting-service:
      path: /posting-service/**
      url: http://localhost:8085/posting-service/
    renting-service:
      path: /renting-service/**
      url: http://localhost:8086/renting-service
    review-service:
      path: /review-service/**
      url: http://localhost:8087/review-service/
    image-service:
      path: /image-service/**
      url: http://localhost:8089/image-service/
    messaging-service:
      path: /messaging-service/**
      url: http://localhost:8083/messaging-service/
    notification-service:
      path: /notification-service/**
      url: http://localhost:8084/notification-service/
