version: '3'
services:

  eureka-serviceregistry:
    build: ./eureka
    ports:
     - "8761:8761"
    tty: true

#  admin-service:
#    build: ./admin-service
#    ports:
#    - "8082:8082"
#    environment:
#      - REGISTRY_HOST=eureka-serviceregistry
#    tty: true
#    depends_on:
#      - eureka-serviceregistry

  auth-service:
    build: ./auth-service
    ports:
    - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  #image-service:
    #build: ./image-service
    #ports:
    #- "8089:8089"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry

  #messaging-service:
    #build: ./messaging-service
    #ports:
    #- "8083:8083"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry

  #notification-service:
    #build: ./notification-service
    #ports:
    #- "8084:8084"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry

  #posting-service:
    #build: ./posting-service
    #ports:
    #- "8085:8085"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry

#  renting-service:
#    build: ./renting-service
#    ports:
#    - "8086:8086"
#    environment:
#      - REGISTRY_HOST=eureka-serviceregistry
#    tty: true
#    depends_on:
#      - eureka-serviceregistry
      
  #review-service:
    #build: ./review-service
    #ports:
    #- "8087:8087"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry
      
  #search-service:
    #build: ./search-service
    #ports:
    #- "8088:8088"
    #environment:
      #- REGISTRY_HOST=eureka-serviceregistry
    #tty: true
    #depends_on:
      #- eureka-serviceregistry

  zuul:
    build: ./Zuul
    ports:
    - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      #- admin-service
      - auth-service
      #- image-service
      #- messaging-service
      #- notification-service
      #- posting-service
      #- renting-service
      #- review-service
      #- search-service

  

  

