eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: notification-service

server:
  port: 8084